// Mocks generated by Mockito 5.4.6 from annotations
// in gallery/test/providers/image_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gallery/models/image.dart' as _i4;
import 'package:gallery/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginationResponse_0<T> extends _i1.SmartFake
    implements _i2.PaginationResponse<T> {
  _FakePaginationResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.PaginationResponse<_i4.ImageModel>> fetchImages({
    int? offset = 0,
    int? limit = 20,
    String? sortBy = 'created_at',
    String? sortDir = 'desc',
    List<int>? tagIds,
    bool? hasTags,
    bool? hasPendingTags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchImages, [], {
              #offset: offset,
              #limit: limit,
              #sortBy: sortBy,
              #sortDir: sortDir,
              #tagIds: tagIds,
              #hasTags: hasTags,
              #hasPendingTags: hasPendingTags,
            }),
            returnValue:
                _i3.Future<_i2.PaginationResponse<_i4.ImageModel>>.value(
                  _FakePaginationResponse_0<_i4.ImageModel>(
                    this,
                    Invocation.method(#fetchImages, [], {
                      #offset: offset,
                      #limit: limit,
                      #sortBy: sortBy,
                      #sortDir: sortDir,
                      #tagIds: tagIds,
                      #hasTags: hasTags,
                      #hasPendingTags: hasPendingTags,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.PaginationResponse<_i4.ImageModel>>);

  @override
  _i3.Future<void> permanentDeleteImage(int? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#permanentDeleteImage, [imageId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
